apiVersion: v1
kind: Service
metadata: 
  name: kubeservice405
spec:  
  selector:
    app: kubeusers405
  ports:
    - port:  80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers405
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers405
  template:
    metadata:
      labels:
        app: kubeusers405
    spec:
      containers:
        - name: kuebecontainer405
          image: defe014/usercreator405:1.0.0
          ports: 
            - containerPort: 8000
          env:
            - name: MONGO_URL
              value: mongodb+srv://Federico:Federico1**@cluster0.r3sreep.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
          imagePullPolicy: Always

